'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property ProductId As Integer
    Public Property ProductName As String
    Public Property Amount As Nullable(Of Integer)
    Public Property CreationDate As Nullable(Of Date)
    Public Property ModificationDate As Nullable(Of Date)
    Public Property Price As Nullable(Of Double)
    Public Property Description As String
    Public Property ProviderId As Nullable(Of Integer)
    Public Property ProviderName As String
    Public Property CategorieId As Nullable(Of Integer)

    Public Overridable Property Categoire As Categoire

End Class
